name: Web
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm ci, build
        run: |
          npm ci
          export NODE_ENV=production && npx webpack
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: upload
          path: |
            web/public
